openapi: 3.0.3
info:
  title: Smart Notes
  description: API for Smart Notes
  version: 0.0.0
components:
  schemas:
    User:
      type: object
      properties:
        id:
          maxLength: 255
          type: string
        name:
          minLength: 1
          maxLength: 255
          type: string
        email:
          format: email
          minLength: 1
          maxLength: 255
          type: string
      required:
        - id
        - name
        - email
paths:
  /api/auth/user:
    get:
      operationId: getUser
      tags:
        - auth
      description: Get current user
      responses:
        2XX:
          description: Default Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
tags:
  - name: auth
    description: Auth related end-points

