/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Smart Notes
 * API for Smart Notes
 * OpenAPI spec version: 0.0.0
 */

export interface User {
  /** @maxLength 255 */
  id: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  email: string;
}
