/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Smart Notes
 * API for Smart Notes
 * OpenAPI spec version: 0.0.0
 */
import type { User } from "../types/api";

import { customInstance } from "../lib/api-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get current user
 */
export const getUser = (options?: SecondParameter<typeof customInstance>) => {
  return customInstance<User>(
    { url: `/api/auth/user`, method: "GET" },
    options,
  );
};
export type GetUserResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;
