/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Swagger API Test
 * Testing the Fastify swagger API
 * OpenAPI spec version: 0.0.0
 */

export interface User {
  /** @maxLength 255 */
  id: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  displayName: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  email: string;
}
